/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */

 
/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  // tutorialSidebar: [{type: 'autogenerated', dirName: '.'}],
  tutorialSidebar: [
    {
      type: "doc",
      id: "intro",
    }
  ],
  api: [
    {
      type: "category",
      label: "API Documentation",
      link: {
        type: "generated-index",
        title: "API",
        description:
          "This is a sample server. You can find out more about Swagger at http://swagger.io or on irc.freenode.net, #swagger. For this sample, you can use the api key special-key to test the authorization filters.",
        slug: "/category/api",
      },
      items: require("./docs/api/sidebar.js"),
    },
    // {
    //   type: "category",
    //   label: "Cloud Object Storage",
    //   link: {
    //     type: "generated-index",
    //     title: "Cloud Object Storage API",
    //     slug: "/category/cos-api",
    //   },
    //   items: require("./docs/cos/sidebar.js"),
    // },
    // {
    //   type: "category",
    //   label: "Burgers",
    //   link: {
    //     type: "generated-index",
    //     title: "Burger API",
    //     slug: "/category/food-api",
    //   },
    //   items: [
    //     {
    //       type: "autogenerated",
    //       dirName: "food/burgers", // '.' means the current docs folder
    //     },
    //   ],
    // },
    // {
    //   type: "category",
    //   label: "Yogurt Store",
    //   link: {
    //     type: "generated-index",
    //     title: "Yogurt Store API",
    //     slug: "/category/yogurt-api",
    //   },
    //   items: [
    //     {
    //       type: "autogenerated",
    //       dirName: "food/yogurtstore", // '.' means the current docs folder
    //     },
    //   ],
    // },
  ],

};

module.exports = sidebars;
