name: Ansible Deployment
on:
  push:
    branches:
      - 'main'
jobs:
  build:
    name: Build images
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v1
      
      - name: Get current date
        id: date
        run: echo "::set-output name=date::$(date +'%Y-%m-%d-%H')"
      
      - name: Test with environment variables
        run: echo $TAG_NAME - $RELEASE_NAME
        env:
          RELEASE_NAME: release-${{ steps.date.outputs.date }}
      
             
      - name: Build docker images of frontend part
        env:
          DOCKER_USERNAME: ${{secrets.DOCKER_USERNAME}}
          DOCKER_PASSWORD: ${{secrets.DOCKER_PASSWORD}}
          RELEASE_NAME: release-${{ steps.date.outputs.date }}
        run: |
          docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
          docker build -t docs-ocplanet-cloud -f ./Dockerfile ./
          docker tag docs-ocplanet-cloud:latest $DOCKER_USERNAME/docs-ocplanet-cloud:latest
          docker tag $DOCKER_USERNAME/docs-ocplanet-cloud:latest $DOCKER_USERNAME/docs-ocplanet-cloud:$RELEASE_NAME
          docker push $DOCKER_USERNAME/docs-ocplanet-cloud:latest
          docker push $DOCKER_USERNAME/docs-ocplanet-cloud:$RELEASE_NAME
      



  deploy:
      name: Deploy image to server
      runs-on: ubuntu-latest
      needs: ['build']
      steps:
        - name: Checkout Code
          uses: actions/checkout@v1
        - name: Run playbook
          uses: dawidd6/action-ansible-playbook@v2
          with:
            playbook: deployment.yml
            directory: ./deployment
            key: ${{secrets.SSH_PRIVATE_KEY}}
            inventory: ${{secrets.INVENTORY}}
            known_hosts: ${{secrets.KNOW_HOSTS}}
            vault_password: ${{secrets.ANSIBLE_VAULET}}
            requirements: requirements.yml